### ISSUE TITLE
“S” hidden when printing time has double-digit minutes and seconds

### ISSUE THREAD

**Issue by Thinkersbluff** [CR6Community/CR-6-touchscreen#33]
Running Rel 6 Pre 4 self-compiled on 21 Feb.

Once the minutes and seconds both show double-digits, the S disappears.  If possible, please increase the field size or shrink the font or reduce the space between minutes and seconds?

![7CD431E7-B74C-44A6-B49A-B61D1979FAEF](https://user-images.githubusercontent.com/36551518/108752468-7d2e1d00-7511-11eb-8ba2-fa727f342f20.jpeg)
![87345FBE-BBA5-4E3D-ACC2-0C09EBF777A2](https://user-images.githubusercontent.com/36551518/108752472-7dc6b380-7511-11eb-8c5a-45b673c29a85.jpeg)

**Comment by Sebazzz** [comment]
Thanks, bbc868e should fix it.

**Comment by Thinkersbluff** [comment]
Sorry.  24 Feb extui Rel.6 Pre 4 not fixed.
![F27BDC14-88D2-4A65-B410-051937BA7E8E](https://user-images.githubusercontent.com/36551518/109073849-f3bf4c00-76c4-11eb-9b9e-475cfff64533.jpeg)

**Comment by Sebazzz** [comment]
For [issue #114](https://github.com/CR6Community/Marlin/issues/114) in the main repository @ztakis is working on a design. I've suggested to him to move the stopwatch icon a bit to the left to accommodate for an even wider label.

**Comment by Thinkersbluff** [comment]
> For [issue #114](https://github.com/CR6Community/Marlin/issues/114) in the main repository @ztakis is working on a design. I've suggested to him to move the stopwatch icon a bit to the left to accommodate for an even wider label.

Well, the good news is you don’t need a wider field and you don’t need to move the stopwatch icon.  
![E7A2F52E-97B1-405C-AD9D-A80FDDCE8263](https://user-images.githubusercontent.com/36551518/109395132-c955d480-78f8-11eb-891e-139fb528b221.jpeg)
 I added a second zero to the Textinit parameter on screens 36, 37 and 39.

Now, I am into a 7-hr print, but will try removing the “s” from that field on the next iteration.  
![B9DEDB18-A7C9-4A02-A056-DC439426A1CD](https://user-images.githubusercontent.com/36551518/109395216-2b163e80-78f9-11eb-834a-970cd06da545.jpeg)

**Comment by Sebazzz** [comment]
Got it, string length was set to 6 at the Marlin side.
